changelog:
  categories:
    - title: Product
      labels:
        - enhancement
        - feature
    - title: Bug Fixes
      labels:
        - bug
        - fix
    - title: Documentation
      labels:
        - docs
    - title: Maintenance
      labels:
        - chore
        - ci
        - dependencies
  exclude:
    labels:
      - skip-changelog
